### ISSUE TITLE
Odd base_footprint_wheel frame floating around?

### ISSUE THREAD

**Issue by damonkohler** [googlecartographer/cartographer_toyota_hsr#8]
While running through the demo bag, I noticed there's a stray frame floating around. Is that intended?

**Comment by macmason** [comment]
Confirmed, but I don't know the answer.

**Comment by athackst** [comment]
base_footprint_wheel is from the wheel odometry. We typically check it out to make sure there isn't too much slippage, but isn't used for anything.

**Comment by macmason** [comment]
Per @athackst, WAI.
